name: "Tweet the Quote"

on:
  push:
    branches: 
      - main
    
  schedule:
    - cron:  '00 22 * * *'
    - cron:  '00 15 * * *'
    - cron:  '00 5 * * *'
    

jobs:
  tweet:
    name: 'Install dependencies and make the tweet'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt
  
      - name: Run the file
        run: python main.py ${{ secrets.CONSUMER_KEY }} ${{ secrets.CONSUMER_SECRET }} ${{ secrets.TOKEN }} ${{ secrets.TOKEN_SECRET }}
        
      - name: Keep alive
        uses: gautamkrishnar/keepalive-workflow@master
