name: "Tweet the Quote"

on:
  schedule:
    - cron:  '00 22 * * *'
    - cron:  '00 14 * * *'
    

jobs:
  tweet:
    name: 'Install dependencies and make the tweet'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt
  
  